# Generated by Django 2.2.7 on 2019-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('day_of_birth', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Birth')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Image')),
                ('pesel', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='PESEL')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), (None, 'Undefined')], default=None, max_length=30, null=True, verbose_name='Gender')),
                ('friend', models.ManyToManyField(to='contacts.Persons', verbose_name='Friend')),
            ],
        ),
    ]
