# Generated by Django 2.2.7 on 2019-12-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, to='contacts.Person', verbose_name='Friends'),
        ),
        migrations.CreateModel(
            name='EmailField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('work', 'work'), ('home', 'home'), ('other', 'other'), (None, None)], default=None, max_length=30, null=True, verbose_name="Email's role")),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
