# Generated by Django 2.2.7 on 2019-12-03 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191202_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('work', 'work'), ('home', 'home'), ('mobile', 'mobile'), ('other', 'other'), (None, None)], default=None, max_length=30, null=True, verbose_name="Phone number's role")),
                ('phone', models.CharField(max_length=60, verbose_name='Phone number')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
            options={
                'verbose_name': 'Phone number',
                'verbose_name_plural': 'Phone numbers',
            },
        ),
    ]
